#!/usr/bin/env node
"use strict";

/**
 * tools/mergePronunciationBank.js
 *
 * Merges all hindi_hinglish_pronunciation_bank_v1_partN.json files in /data
 * into a single deduplicated, sorted pronunciation_master.json.
 *
 * Usage:
 *   node tools/mergePronunciationBank.js
 *
 * Run this whenever you add new pronunciation bank part files.
 * The output file (data/pronunciation_master.json) is what the live engine reads.
 */

const fs   = require("fs");
const path = require("path");

const DATA_DIR     = path.join(__dirname, "..", "data");
const OUTPUT_FILE  = path.join(DATA_DIR, "pronunciation_master.json");
const PART_PATTERN = /^hindi_hinglish_pronunciation_bank.*\.json$/i;

// Risk priority for deduplication (higher = preferred when normalised_word collides)
const RISK_RANK = { high: 3, medium: 2, low: 1 };

// ── Helpers ───────────────────────────────────────────────────────────────────

function normaliseKey(word) {
  return String(word || "").toLowerCase().trim();
}

function stripHyphens(phonetic) {
  // Phonetic versions in the bank use hyphens as syllable separators (documentation).
  // Strip them to produce TTS-safe spelling hints.
  return String(phonetic || "").replace(/-/g, "");
}

function wordCount(str) {
  return (str.match(/\S+/g) || []).length;
}

// ── Load all part files ───────────────────────────────────────────────────────

const partFiles = fs.readdirSync(DATA_DIR)
  .filter(f => PART_PATTERN.test(f) && f !== "pronunciation_master.json")
  .sort();

if (!partFiles.length) {
  console.error("No pronunciation bank part files found in", DATA_DIR);
  process.exit(1);
}

console.log(`Found ${partFiles.length} part file(s):`, partFiles.join(", "));

let allEntries = [];
for (const f of partFiles) {
  try {
    const raw  = JSON.parse(fs.readFileSync(path.join(DATA_DIR, f), "utf8"));
    const bank = raw.pronunciation_bank || [];
    allEntries = allEntries.concat(bank);
    console.log(`  ${f}: ${bank.length} entries`);
  } catch (e) {
    console.error(`  Failed to read ${f}: ${e.message}`);
  }
}

console.log(`Total raw entries: ${allEntries.length}`);

// ── Deduplicate on normalised_word ────────────────────────────────────────────
// When the same word appears in multiple parts, keep the highest-risk entry
// (highest-risk = we need to process it most carefully).

const dedupMap = new Map();
for (const entry of allEntries) {
  const key = normaliseKey(entry.normalized_word || entry.word);
  if (!key) continue;

  const existing = dedupMap.get(key);
  const newRank  = RISK_RANK[entry.tts_risk_score] || 0;
  const oldRank  = existing ? (RISK_RANK[existing.tts_risk_score] || 0) : -1;

  if (!existing || newRank > oldRank) {
    dedupMap.set(key, {
      word:                entry.word || key,
      normalized_word:     key,
      phonetic_version:    entry.phonetic_version || "",
      phonetic_tts:        stripHyphens(entry.phonetic_version || ""),  // ready-to-use form
      language_type:       entry.language_type || "Hindi",
      category:            entry.category || "general",
      replace_with_if_needed: entry.replace_with_if_needed || "",
      tts_risk_score:      entry.tts_risk_score || "medium",
    });
  }
}

console.log(`After deduplication: ${dedupMap.size} unique entries`);

// ── Sort: longest phrases first, then alphabetical within same word-count ─────
const sorted = Array.from(dedupMap.values()).sort((a, b) => {
  const wa = wordCount(a.normalized_word);
  const wb = wordCount(b.normalized_word);
  if (wa !== wb) return wb - wa;  // more words → higher priority
  return a.normalized_word.localeCompare(b.normalized_word);
});

// ── Build stats ───────────────────────────────────────────────────────────────
const stats = { total: sorted.length, high: 0, medium: 0, low: 0, phrases: 0, singleWords: 0 };
for (const e of sorted) {
  stats[e.tts_risk_score] = (stats[e.tts_risk_score] || 0) + 1;
  if (e.normalized_word.includes(" ")) stats.phrases++;
  else stats.singleWords++;
}

// ── Write output ──────────────────────────────────────────────────────────────
const output = {
  meta: {
    generated:    new Date().toISOString(),
    source_files: partFiles.length,
    ...stats,
    note: "Auto-generated by tools/mergePronunciationBank.js — do not edit manually.",
  },
  pronunciation_bank: sorted,
};

fs.writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), "utf8");

console.log("\n✓ Written:", OUTPUT_FILE);
console.log("  Stats:", JSON.stringify(stats));
console.log("\nTo add new words: create a new part file in /data and re-run this script.");
